global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
